datasources:
  default:
    url: jdbc:postgresql://postgres:cfITGFFqJyIoZWawTFLPlnqWbgWeoMoG@postgres.railway.internal:5432/railway
    username: postgres
    password: cfITGFFqJyIoZWawTFLPlnqWbgWeoMoG
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect  # Fully qualified dialect
    schema-generate: CREATE
    dialect-options:
      ssl: false

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
