micronaut:
  application:
    name: my-app

datasources:
  default:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: cfITGFFqJyIoZWawTFLPlnqWbgWeoMoG
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    dialect-options:
      ssl: false  # Set to true if Railway requires SSL

jpa:
  default:
            properties:
              hibernate:
                bytecode:
                  provider: none
            packages-to-scan:
              - 'my.app.models' # Adjust to your entity package

logger:
  levels:
    io.micronaut.data.query: DEBUG
    io.micronaut.sql: DEBUG
