datasources:
  default:
    url: jdbc:mysql://localhost:3306/author_book_management_system
    username: root
    password: Aa161616
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: MYSQL
    schema-generate: CREATE
    dialect-options:
      ssl: false

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
