datasources:
  default:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: CREATE
    dialect-options:
      ssl: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
