datasources:
  default:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: cfITGFFqJyIoZWawTFLPlnqWbgWeoMoG
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
    dialect-options:
      ssl: false  # or true, depending on Railway's requirements
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
